server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /auth/api/ {
        proxy_pass http://backend:5000/auth/api/;
    }

    location /cliente/api/ {
        proxy_pass http://backend:5000/cliente/api/;
    }

    location /producto/api/ {
        proxy_pass http://backend:5000/producto/api/;
    }

    location /inventario/api/ {
        proxy_pass http://backend:5000/inventario/api/;
    }

    location /pedidos/api/ {
        proxy_pass http://backend:5000/pedidos/api/;
    }
}
